#
#  JSONCC_INCLUDE_DIRS - where to find json.hpp, etc.
#  JSONCC_LIBRARIES    - List of libraries when using json.
#  JSONCC_FOUND        - True if json found.

IF (JSONCC_INCLUDE_DIRS)
  # Already in cache, be silent
  SET(JSONCC_FIND_QUIETLY TRUE)
ENDIF (JSONCC_INCLUDE_DIRS)

FIND_PATH(JSONCC_INCLUDE_DIR json/json.hpp)

SET(JSONCC_NAMES json)
FIND_LIBRARY(JSONCC_LIBRARY NAMES ${JSONCC_NAMES} )

# handle the QUIETLY and REQUIRED arguments and set JSONCC_FOUND to TRUE if 
# all listed variables are TRUE
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(JSONCC DEFAULT_MSG JSONCC_LIBRARY JSONCC_INCLUDE_DIR)

IF(JSONCC_FOUND)
  SET( JSONCC_LIBRARIES ${JSONCC_LIBRARY} )
  SET( JSONCC_INCLUDE_DIRS ${JSONCC_INCLUDE_DIR} )
ELSE(JSONCC_FOUND)
  SET( JSONCC_LIBRARIES )
  SET( JSONCC_INCLUDE_DIRS )
ENDIF(JSONCC_FOUND)

MARK_AS_ADVANCED( JSONCC_LIBRARIES JSONCC_INCLUDE_DIRS )
